### ISSUE TITLE
Cannot use parse_mail() to parse mails from File because of lifetimes

### ISSUE THREAD

**Issue by matthiasbeyer** [staktrace/mailparse#1]
Doing

```rust
pathes.iter()
    .map(|path| {
        let mut buf;
        File.open(path).read_to_end(&mut buf);
        parse_mail(&buf)
    })
```
is not possible because the lifetime of the result of `parse_mail()` requires the `buf` to outlife the function.

Can we have an interface which does not require this, please? It is really hard to use this crate otherwise.

**Comment by matthiasbeyer** [comment]
As far as I can see, this is because you work with `&[u8]` down to the very core types of this library. So the whole setup of the library is the issue here, as far as I can see.

**Comment by staktrace** [comment]
Use of &[u8] is intentional to avoid allocation extra memory unnecessarily. If you provide a more complete example of what you're trying to do (with mostly-compiling code) I can try to provide more useful help. In my [mailparse-bin](https://github.com/staktrace/mailparse-bin/blob/master/src/main.rs) repo you can find an example of how to use the library to process a bunch of files (provided as command line input, in this case).

**Comment by matthiasbeyer** [comment]
I'm trying to write a wrapper around your library to handle Maildirs from Rust, with a high-level API: https://github.com/matthiasbeyer/maildirparse

The problem is, that a user should be able to build a `Maildir` object from a `PathBuf` which points to a valid maildir on the filesystem. I then want to be able to say

```rust
let md = Maildir::new(PathBuf::from("/home/user/examplemaildir/"));
md.new_mails()
```

where `Maildir::new_mails()` returns a `Result<Vec<ParsedMail>>`. But as `ParsedMail` has a lifetime bound to the `str` that is the content of the file on filesystem, I cannot do that. At least I cannot do the IO on `new_mails()` - one possible way to do this is loading everything to RAM when `Maildir::new()` is called - but you already see that this is not nice, at it would cause a _lot_ of IO even if the user of the library just wants to find the new mails.

**Comment by staktrace** [comment]
So I'm also in the process of writing a maildir library. The way I'm going about it is returning an iterator over the individual mail files, which works just fine. I'm not very far along but you can see my code in [my repo](https://github.com/staktrace/maildir/blob/master/src/lib.rs). The way you're doing it, it looks like it's still going to load all of the new mails into RAM simultaneously which I avoid. However, that's a side issue.

To address the root of your question, the reason I made the lifetimes the way I did was that I intended the `ParsedMail` struct to be a lightweight wrapper over top of the data buffer - internally it just references the data buffer rather than copying the data over. Thus it is cheap on memory although the caller is responsible for keeping the data buffer around. In my maildir library I do that by having the `MailEntry` struct own the data buffer, and produce those `MailEntry` structs when iterating through the `MailEntries` iterator. You can do something similar by having your new_mails() function produce `Vec` of an intermediate struct that owns the data buffer, instead of the `Vec` holding the `ParsedMail` objects directly.

**Comment by matthiasbeyer** [comment]
That sounds like a good idea, yes. I will have a closer look at your maildir library, though.

**Comment by staktrace** [comment]
Ok. I'll close this issue for now, we can reopen it later if necessary. Note that at the moment I'm pretty busy so my maildir library is progressing slowly - hopefully in a couple of weeks I'll have more time to spend on it.

**Comment by matthiasbeyer** [comment]
This issue still exists. This simple program does not compile, although this is the absolute standard-usecase:

```
use anyhow::Error;
use anyhow::Result;
use cursive::CursiveExt;
use mailparse::MailHeaderMap;
use std::ops::Deref;

fn list_view_for<'a, I>(i: I) -> Result<cursive::views::ListView>
    where I: IntoIterator<Item = Result<mailparse::ParsedMail<'a>>>
{
    let mut lv = cursive::views::ListView::new();

    for elem in i {
        let elem = elem?;
        let s = format!("{}: {} -> {} | {}",
            elem.headers.get_first_value("Date").unwrap_or_else(|| String::from("No date")),
            elem.headers.get_first_value("From").unwrap_or_else(|| String::from("No From")),
            elem.headers.get_first_value("To").unwrap_or_else(|| String::from("No To")),
            elem.headers.get_first_value("Subject").unwrap_or_else(|| String::from("No Subject")));

        lv.add_child("", cursive::views::TextView::new(s));
    }

    Ok(lv)
}

fn main() -> Result<()> {
    let maildir_path = "/home/USER/mail/path";

    let md = maildir::Maildir::from(maildir_path);
    let iter = md.list_cur()
        .map(|r| r.map_err(Error::from).and_then(|mut r| r.parsed().map_err(Error::from)));
    let view = list_view_for(iter)?;

    let mut siv = cursive::Cursive::default();
    siv.add_layer(view);
    siv.add_global_callback('q', |s| s.quit());
    siv.run();

    Ok(())
}
```

**Comment by matthiasbeyer** [comment]
I fought two hours against the API now, simply trying to load a list of mails from disk and show it in cursive (using the `maildir` crate and trying to load the bytes myself from disk). I'm giving up now.
