### ISSUE TITLE
Reuse `hyper::headers` 

### ISSUE THREAD

**Issue by sanmai-NL** [staktrace/mailparse#16]
For example, take `Content-Disposition`.

Instead of [reinventing the wheel](https://docs.rs/mailparse/0.6.0/mailparse/struct.ParsedContentDisposition.html), could we reuse the [`hyper` `header` module](https://docs.rs/hyper/0.11.9/hyper/header/index.html)? 

```rust
use hyper::header::{Header, Headers, ContentDisposition, DispositionType, DispositionParam, Raw};
```

The `hyper` items are more structured already. See also [RFC 6266](https://tools.ietf.org/html/rfc6266).

**Comment by staktrace** [comment]
I'd rather not use `hyper::header` because it pulls in the entire hyper crate and recursive dependencies which is overkill for something like `mailparse`. Having a small set of cumulative dependencies is something I actively strive for. I try not to take it to extremes but in this case it doesn't seem worth it. I admit that the `Content-Disposition` bit of `mailparse` could probably use some improvements as it was only added recently, but in this case reusing HTTP structures for MIME content doesn't seem appropriate to me. If you have other suggestions on how to improve this I'd be happy to consider them.

**Comment by sanmai-NL** [comment]
@staktrace: please read https://github.com/hyperium/hyper/issues/189 to answer your concerns.
