### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jibaku** [staktrace/mailparse#17]
Hello,

It would be great to and a LICENSE file to make code re-use easier.

Thanks

**Comment by staktrace** [comment]
The Cargo.toml states the license is 0BSD. Is that not sufficient? That seems to be the convention for rust crates, and personally I find it confusing if projects use both a LICENSE file and a license name in Cargo.toml since then it's more ambiguous as to which takes precedence in case of a mismatch.

**Comment by jibaku** [comment]
Ok, it's just as a Rust beginner, I was not aware of the convention. And having a LICENSE File also display it in the github page. But I will know how to get a crate license right now.

**Comment by staktrace** [comment]
Great. Also for reference the license identifier in Cargo.toml file can be used to get the full license text from https://spdx.org/licenses/
