### ISSUE TITLE
Allow get_body() for "binary" encoding

### ISSUE THREAD

**Issue by vickenty** [staktrace/mailparse#51]
Currently, `ParsedMail::get_body()` returns an error if `binary` content encoding was used. There are some messages that I'm trying to parse that use `binary` encoding for `text/plain`, and I think it would make sense if `get_body()` would work for them too.

According to [RFC1341](https://tools.ietf.org/html/rfc1341), there is no actual distinction between `8bit` and `binary` transfer encodings except the limitation on line length. The text seems to suggest that `8bit` and `binary` should be used to indicate type of the payload, but there is no requirement to do so.

If this makes sense, I can work on a PR to fix this.

Thanks!

**Comment by staktrace** [comment]
Hm, this is a bit of a grey area I guess. I see what you mean about the RFC saying they are basically equivalent, but I think that's an equivalence at the SMTP layer, vs equivalence at a higher layer. The RFC also says

> (e.g.,  "8bit"
> for unencoded 8 bit wide data).  If the body contains binary
> data, the "binary" Content-Transfer-Encoding token  must  be
> used.

So this seems to imply that there is a distinction between "unencoded 8 bit wide data" and "binary data" that matters at some level. Conceptually I think it makes sense that "binary" refers to non-text data, which doesn't make sense to convert to UTF-8 and put into a Rust string.

I'm open to arguments but as it stands I don't think it makes sense to make this change. You can use `get_body_raw()` instead of `get_body()` to get back a `Vec<u8>` and then convert it to a Rust string on your end if you feel it is safe to do so.

**Comment by lorenz** [comment]
The difference between `8bit` and `binary` is defined in [RFC2045](https://tools.ietf.org/html/rfc2045#section-2.8).

Basically `binary` drops the line length limitation and thus requires no specific line endings. It also additionally allows unrestricted use of the CR and LF control characters and the NUL character.

I can send binary data in `8bit` just fine, it just has to contain CRLF at least every 999 bytes and no NULs. There's no requirement that it's valid text in some encoding.

The content type (i.e. text or binary data) is only indicated by the `Content-Type` header. Excerpt from RFC2045:
```
NOTE: The five values defined for the Content-Transfer-Encoding field
   imply nothing about the media type other than the algorithm by which
   it was encoded or the transport system requirements if unencoded.
```
RFC2045 also mentions that at the time of writing (1996) it's invalid to use `binary` since there's no standardized transport protocol that can carry these parts. This has since changed with RFC3030 (back in 2000) which is an ESMTP extension allowing transmission of this encoding.

So today it's perfectly valid to transmit and store any data (including text) as `binary` `Content-Transfer-Encoding`. I also see different mail clients transferring text as `Content-Transfer-Encoding: binary` since it imposes the least amount of complexity onto the client as plain UTF8 is already valid in that format.

**Comment by staktrace** [comment]
I'll reopen this for now. I'm not convinced yet but I'll take a look at the specs you're referencing in closer detail when I have more time.

**Comment by staktrace** [comment]
Sorry for the delay here. It kind of dropped off my radar. Anyway I gave this some more thought and decided to allow this behaviour, mostly on the grounds that `mailparse` is supposed to allow dealing with real-world use cases where reasonable, even if they bend/violate the rules of the spec. So in that respect it makes sense for the API to allow getting a binary body as a rust string since there seem to be real-world use cases where that is a thing. It may not always work, but it's up to the caller to handle errors gracefully.

I have a patch coming.

**Comment by lorenz** [comment]
One less patch to maintain :)

> even if they bend/violate the rules of the spec
The way I interpret the RFCs this is perfectly acceptable. I would not call this bending or violating any specs. I've quoted RFC2045 above which explicitly says this is ok.

>  It may not always work, but it's up to the caller to handle errors gracefully.
This is totally fine, obviously not all content can be converted to a Rust String. A caller should inspect the content type to see if it expects a string. But this is also true for all other encodings like 8bit and 7bit since after decoding them they can represent arbitrary binary data (and I've had cases where the decoded content was not a valid string despite being encoded in 7bit).

Anyways, thanks for the great library! I've parsed the entirety of LKML (20 years and 21GiB of real-world and sometimes exotic mail) with it and other than this small issue it performed formidably.
