### ISSUE TITLE
Question: Is it possible to parse a stream of data line by line?

### ISSUE THREAD

**Issue by inashivb** [staktrace/mailparse#87]
Hi!

I am trying to use mailparse while writing a parser for SMTP protocol. So far, I have been buffering the entire e-mail up and sending it at once as an argument to `parse_mail` function. This is OK for many usual situations but is troublesome when the e-mail is wayyy too big. Is it possible to parse the email line by line as it is sent over?

**Comment by staktrace** [comment]
I'd need a bit more context to answer more specifically, but here's some thoughts:

Parsing the entire mail in-memory will by definition require storing the entire mail in memory. `mailparse` itself should be zero-copy, so once you buffer up the entire email into memory and hand it to `parse_mail`, it shouldn't require significant extra memory even if the email is large. Presumably the problem you're running into is that the email is too big to store in memory. So my question then is, what information do you actually need from `mailparse`? Are you e.g. just extracting some header information, or do you need to look at all the body parts/subparts?

If you're just extracting headers, then you can use the [`parse_headers` function](https://docs.rs/mailparse/0.13.3/mailparse/fn.parse_headers.html) instead. It doesn't do line-by-line, but you can instead buffer say the first 100 lines or 4kb or so (or whatever you think is a reasonable amount that should include all the headers) and pass that to `parse_headers` to get just the headers parsed.

If you need the entire body parsed, and you can't store the entire email in-memory, then pretty much the only other option is to store it on disk, memory map the file, and then give that to `mailparse`. I know this approach can be made to work as I've used it [in `maildir` here](https://github.com/staktrace/maildir/blob/a69314984a205dfc80cb2f79e5f66c2a6f18f6eb/src/lib.rs#L120-L121). I don't know if it can be applied to your specific scenario though since I don't know what your overall mail handling process is.

**Comment by inashivb** [comment]
> I'd need a bit more context to answer more specifically, but here's some thoughts:
> 
> Parsing the entire mail in-memory will by definition require storing the entire mail in memory. `mailparse` itself should be zero-copy, so once you buffer up the entire email into memory and hand it to `parse_mail`, it shouldn't require significant extra memory even if the email is large. Presumably the problem you're running into is that the email is too big to store in memory. So my question then is, what information do you actually need from `mailparse`? Are you e.g. just extracting some header information, or do you need to look at all the body parts/subparts?
> 
Yes.  I also need to know when the body has ended and if the body was successfully parsed.
In an attacker's scenario, I learned that any large number of headers could be sent so storing them could also be a pain.

> If you're just extracting headers, then you can use the [`parse_headers` function](https://docs.rs/mailparse/0.13.3/mailparse/fn.parse_headers.html) instead. It doesn't do line-by-line, but you can instead buffer say the first 100 lines or 4kb or so (or whatever you think is a reasonable amount that should include all the headers) and pass that to `parse_headers` to get just the headers parsed.
> 
Thank you. I thought about it but wasn't sure how to go about getting info about the body.

> If you need the entire body parsed, and you can't store the entire email in-memory, then pretty much the only other option is to store it on disk, memory map the file, and then give that to `mailparse`. I know this approach can be made to work as I've used it [in `maildir` here](https://github.com/staktrace/maildir/blob/a69314984a205dfc80cb2f79e5f66c2a6f18f6eb/src/lib.rs#L120-L121). I don't know if it can be applied to your specific scenario though since I don't know what your overall mail handling process is.
Oh! Thanks a lot. This might be useful. I'll have to check in with my mentor though. I'll get back about this on Monday.

**Comment by staktrace** [comment]
I'm going to close this out since it doesn't seem actionable on my part. If you have follow-up questions feel free to ask though!
