### ISSUE TITLE
unexpected postfix "\r" in MailHeader's value field

### ISSUE THREAD

**Issue by qsdgy** [staktrace/mailparse#90]
e.g.,

```rust
"X-IncomingHeaderCount: 10\r\n"
```

would be parsed to

```rust

MailHeader {
            key: "X-IncomingHeaderCount",
            value: "10\r",
}

```

**Comment by qsdgy** [comment]
[trim()](https://doc.rust-lang.org/std/primitive.str.html#method.trim) is bad as it removes `SPACE`s in content of value

**Comment by staktrace** [comment]
What API are you using to do the parsing?

**Comment by qsdgy** [comment]
[mailparse::parse_mail()](https://docs.rs/mailparse/0.13.4/mailparse/fn.parse_mail.html) mail is dump from outlook.com

```rust
let mut f = File::open("mail.dat")?;
let mut buffer = Vec::new();
f.read_to_end(&mut buffer)?;
let parsed = parse_mail(&buffer).unwrap();
```

**Comment by staktrace** [comment]
Can you attach a (maybe sanitized) mail.dat file that reproduces the problem? There are existing tests in the library that exercise this so I'm kind of surprised you're seeing this problem. I can understand seeing the problem with `parse_header` but if you're seeing it with `parse_mail` that's very unexpected to me.

**Comment by staktrace** [comment]
Oh, I see. You have to use `.get_value()` instead of `.value` to get the value without the trailing `\r`. The `.value` field just has raw bytes from the input mail, and can potentially be encoded as well. So that's probably not what you want.

**Comment by qsdgy** [comment]
Here's the [mail](https://github.com/staktrace/mailparse/files/6780888/mail.zip).

I'm using `MailHeader::get_value()` in present, and it works fine.

One may tend to use `MailHeader::get_value_raw()` to get `&[u8]` in scenarios that don't need ownership. It would be fine if the `value` returned by `get_value_raw()` just points to what exactly value content is.

**Comment by qsdgy** [comment]
Oh, maybe raw bytes without trailing `"\r"` just meanless with multi-line values, one handles `"line\r\n line"` likely don't mind to handle `"line\r\n line\r"` or `"\r\n line\r\n line\r"`, there's a bit more convenience in single-line processing.

If striping trailing `"\r"` and leading `"\r\n "`  is't a pain in touching implementation details, it would be great if this crate does this.

**Comment by staktrace** [comment]
> One may tend to use `MailHeader::get_value_raw()` to get `&[u8]` in scenarios that don't need ownership.

But note that `get_value()` and `get_value_raw()` differ in more than just ownership of returned value. Header values may have encoded words in them, and `get_value_raw()` doesn't do decoding whereas `get_value()` does. See [this test case](https://github.com/staktrace/mailparse/blob/988b703124de4be9b603935e8ffcc49bb2b816bf/src/lib.rs#L994) for an example. If you're using `get_value_raw()` then you're responsible for doing the decoding yourself, and that's non-trivial, so you might as well so the whitespace collapsing as well.

 If you ignore the encoding problem then yes I understand that it would be more convenient for single line processing if the implementation stripped out the `\r`. It's a pretty specific use case though. I'll leave this issue open for now, I think it might be possible to do without too much effort, but if it turns out to be complicated I likely won't do it.

**Comment by qsdgy** [comment]
It's very kind of you having a look at it. 

Although `MailHeader::get_value()` is working well, I open this issue to leave the door open to make my code referring raw bytes as what `mailparse` does instead of holding `String`s (may far more later), for most headers I'm dealing with are simple plain  `7bit` text (`Date`,`From` ,`To`, and `Subject`), it helps gain good taste of code.

**Comment by staktrace** [comment]
Ok, I landed a patch that should remove the trailing `\r` from header values that don't wrap into new lines. Hope that works for you! I'll put out a new release in a few days, I have another fix I'm working on that I'd like to get in first.
