### ISSUE TITLE
Support `no_std` feature

### ISSUE THREAD

**Issue by zzhengzhuo** [staktrace/mailparse#93]
Is there any plan to support `no_std` feature?

**Comment by staktrace** [comment]
It's not something I have considered. If it's not a lot of work I wouldn't be opposed to it though.

**Comment by zzhengzhuo** [comment]
staktrace/quoted-printable#9

**Comment by staktrace** [comment]
I don't think there's any real alternative to use instead of `charset`. I used to use `encoding_rs` but conceptually it is a little different and hsivonen submitted https://github.com/staktrace/mailparse/pull/32 to migrate to `charset`. If `charset` doesn't support `no_std` you'd have to make that happen first, I guess.

**Comment by zzhengzhuo** [comment]
I can submit a pr hsivonen/charset#5 for `charset`,but I don't know it will accept.

**Comment by staktrace** [comment]
Closing for now. Feel free to reopen if you get the `charset` PR merged.
